In [1]:
import wget
import ssl
import os
ssl._create_default_https_context = ssl._create_unverified_context

In [2]:
# Enter NCRB Individual PDF url
pdf_url = 'https://ncrb.gov.in/sites/default/files/adsi_reports_previous_year/Table-1.0_2019.pdf'
fileName = pdf_url[67:]
try:
    #Delete the file to redownload it
    os.remove(fileName)
except FileNotFoundError as e:
    #Ignore in case FileNotFound Error occurs
    pass
# Download report
fileName = wget.download(pdf_url,fileName)

In [3]:
import numpy as np
import pandas as pd
import camelot

In [4]:
fileName

'Table-1.0_2019.pdf'

In [5]:
tables = camelot.read_pdf(fileName,
    flavor='stream',
    table_areas=[
        "56.75437802907916,671.7985151700498,547.3430694668822,82.11931584024649"
        ],
    columns=[
        "74,248.18016155088856,294.3532148626818,361.6889176090469,417.4813570274637,492.5125686591277"
        ],
    row_tol=10,
    split_text=True,
    strip_text='\n',
    pages="all"
)

In [6]:
tables

In [7]:
def printnAllTables(tables):
    for i in range(len(tables)):
        print("Page No: ",(i+1))
        print(tables[i].df)
        print()

In [8]:
# Incase we're intersted in seeing the original scraped tables.
# Commented as it takes too much screen space
# Run if you want
# printnAllTables(tables)
tables[0].df

,0,1,2,3,4,5,6
0,A.,FORCES OF NATURE,,,,,
1,1,Avalanche,5,0.1,35,0.4,600.0
2,2,Exposure to Cold,757,11.0,796,9.8,5.2
3,3,Cyclone,125,1.8,33,0.4,-73.6
4,4,Tornado,36,0.5,15,0.2,-58.3
5,5,Tsunami,0,0.0,0,0.0,-
6,6,Earthquake,0,0.0,1,0.0,-
7,7,Epidemic,0,0.0,1,0.0,-
8,8,Flood,500,7.3,948,11.6,89.6
9,9,Heat/Sun Stroke,890,12.9,1274,15.6,43.1
10,10,Landslide,404,5.9,264,3.2,-34.7
11,11,Lightning,2357,34.2,2876,35.3,22.0
12,12,Torrential Rain,101,1.5,69,0.8,-31.7
13,13,Forest Fire,10,0.1,9,0.1,-10.0
14,14,Causes other than above,1706,24.8,1824,22.4,6.9
15,15,Total (A),6891,100.0,8145,100.0,18.2
16,B.,OTHER CAUSES,,,,,
17,1,Air-Crash,15,0.0,12,0.0,-20.0
18,2,Ship Accidents,0,0.0,0,0.0,-
19,3,Collapse of Structure,2017,0.5,1929,0.5,-4.4
20,4,Drowning,30187,7.5,32671,7.9,8.2
21,5,Electrocution,12154,3.0,13432,3.3,10.5
22,6,Accidental Explosion,696,0.2,655,0.2,-5.9
23,7,Falls,20201,5.0,20901,5.1,3.5
24,8,Factory/Machine Accidents,1063,0.3,1001,0.2,-5.8
25,9,Accidental Fire,12748,3.1,10915,2.6,-14.4
26,10,Firearm,528,0.1,320,0.1,-39.4
27,11,Mines or Quarry Disaster,125,0.0,82,0.0,-34.4
28,12,Traffic Accidents,178832,44.2,181113,43.9,1.3
29,13,Stampede,6,0.0,12,0.0,100.0
30,14,Sudden Deaths,45634,11.3,47295,11.5,3.6
31,15,Deaths of Women during Pregnancy,1146,0.3,1160,0.3,1.2
32,16,Deaths due to Consumption of Illicit/Poisonou...,1365,0.3,1296,0.3,-5.1
33,17,Killed by Animals,1130,0.3,1425,0.3,26.1
34,18,Poisoning,21646,5.3,21196,5.1,-2.1
35,19,Suffocation,1921,0.5,1598,0.4,-16.8
36,20,Drug Overdose,875,0.2,704,0.2,-19.5
37,21,Causes Not Known,14634,3.6,58576,14.2,300.3
38,22,Causes other than above,58010,14.3,16666,4.0,-71.3
39,,Total (B),404933,100.0,412959,100.0,2.0
40,,Grand Total (A+B),411824,100.0,421104,100.0,2.3

In [9]:
# List of Column headers as column are nested, i.e exhibit a multi level/index structure
# The multi level structre will be generated and applied in the next 
column_header = [
    "Air Crash",
    "Ship Accidents",
    "Collapse of Structure(Total)",
    "Collapse of Structure (Dwelling House/Residential building)",
    "Collapse of Structure (Official/Commercial Building)",
    "Collapse of Structure (Dam)",
    "Collapse of Structure (Bridge)",
    "Collapse of Structure (Others)",
    "Drowning (Total)",
    "Drowning (Boat Capsize)",
    "Drowning (Accidental Falls into Water body)",
    "Drowning (Other Cases)",
    "Electrocution",
    "Accidental Explosion (Total)",
    "Accidental Explosion (Domestic Gas Cylinder)",
    "Accidental Explosion (Industrial Boiler/Gas Cylinder Explosion)",
    "Accidental Explosion (Ammunition Explosion in Armed Forces/Police/CPMF)",
    "Accidental Explosion (Other)",
    "Falls (Total)",
    "Falls (from Height)",
    "Falls (from Vehicles (Automobile like Bus, Trucks, etc.))",
    "Falls (into Manhole)",
    "Falls (into Pit)",
    "Falls (into Borewell)",
    "Falls (Others)",
    "Factory / Machine Accidents",
    "Accidental Fire (Total)",
    "Accidental Fire (Electrical Short Circuit",
    "Accidental Fire (Riot/Agitation)",
    "Accidental Fire (Fireworks)",
    "Accidental Fire (Cooking Gas Cylinder/Stove Burst)",
    "Accidental Fire (Other Causes)",
    "Firearm",
    "Mines or Quarry Disaster",
    "Traffic Accidents (Total)",
    "Road Accidents",
    "Railway Crossing Accidents",
    "Railway Accidents",
    "Stampede",
    "Sudden Deaths (Total)",
    "Sudden Deaths (Heart Attack)",
    "Sudden Deaths (Others)",
    "Deaths of Women during Pregnancy (Total)",
    "Deaths of Women during Pregnancy (Due to Abortions)",
    "Deaths of Women during Pregnancy (Other than Abortions)",
    "Deaths due to Consumption of Illicit/Spurious Liquor",
    "Killed / Injured by Animals",
    "Poisoning (Total)",
    "Poisoning (Food Poisoning)",
    "Poisoning (Accidental Intake of Insecticides/Pesticides)",
    "Poisoning [Poisonous Gases (Total)]",
    "Poisoning [Poisonous Gases (Carbon Monoxide (CO) Gas)]",
    "Poisoning [Poisonous Gases (Other poisonous Gases)]",
    "Poisoning (Snake Bite)",
    "Poisoning (Animal/Reptiles/Insects Bite)",
    "Poisoning (Other)",
    "Suffocation",
    "Drug Overdose",
    "Other than above Causes",
    "Causes Not Known",
    "Total"
]
len(column_header)

61

In [10]:
column_list = [
    ("Sl. No.",''),
    ("Causes",''), 
    ('2018','No.'),
    ('2018','% Share(w.r.t. All India)'),
    ('2019','No.'),
    ('2019','% Share(w.r.t. All India)'),
    ('% Variation during 2019 over 2018','')
]
tables[0].df.columns = pd.MultiIndex.from_tuples(column_list)

In [11]:
# Incase we're intersted in seeing the scraped tables at this point.
# Commented as it takes too much screen space
# Run if you want
# printnAllTables(tables)

# OR Print a simgle one according to your choice
tables[0].df

   Sl. No.                                             Causes    2018  \
                                                                  No.
0       A.                                   FORCES OF NATURE
1        1                                          Avalanche       5
2        2                                   Exposure to Cold     757
3        3                                            Cyclone     125
4        4                                            Tornado      36
5        5                                            Tsunami       0
6        6                                         Earthquake       0
7        7                                           Epidemic       0
8        8                                              Flood     500
9        9                                    Heat/Sun Stroke     890
10      10                                          Landslide     404
11      11                                          Lightning    2357
12      12                                    Torrential Rain     101
13      13                                        Forest Fire      10
14      14                            Causes other than above    1706
15      15                                          Total (A)    6891
16      B.                                       OTHER CAUSES
17       1                                          Air-Crash      15
18       2                                     Ship Accidents       0
19       3                              Collapse of Structure    2017
20       4                                           Drowning   30187
21       5                                      Electrocution   12154
22       6                               Accidental Explosion     696
23       7                                              Falls   20201
24       8                          Factory/Machine Accidents    1063
25       9                                    Accidental Fire   12748
26      10                                            Firearm     528
27      11                           Mines or Quarry Disaster     125
28      12                                  Traffic Accidents  178832
29      13                                           Stampede       6
30      14                                      Sudden Deaths   45634
31      15                   Deaths of Women during Pregnancy    1146
32      16  Deaths due to Consumption of  Illicit/Poisonou...    1365
33      17                                  Killed by Animals    1130
34      18                                          Poisoning   21646
35      19                                        Suffocation    1921
36      20                                      Drug Overdose     875
37      21                                   Causes Not Known   14634
38      22                            Causes other than above   58010
39                                                  Total (B)  404933
40                                          Grand Total (A+B)  411824

                                2019                            \
   % Share(w.r.t. All India)     No. % Share(w.r.t. All India)
0
1                        0.1      35                       0.4
2                       11.0     796                       9.8
3                        1.8      33                       0.4
4                        0.5      15                       0.2
5                        0.0       0                       0.0
6                        0.0       1                       0.0
7                        0.0       1                       0.0
8                        7.3     948                      11.6
9                       12.9    1274                      15.6
10                       5.9     264                       3.2
11                      34.2    2876                      35.3
12                       1.5      69                       0.8
13                       0.1       9                       0.1
14                      24.8    1824                      22.4
15                     100.0    8145                     100.0
16
17                       0.0      12                       0.0
18                       0.0       0                       0.0
19                       0.5    1929                       0.5
20                       7.5   32671                       7.9
21                       3.0   13432                       3.3
22                       0.2     655                       0.2
23                       5.0   20901                       5.1
24                       0.3    1001                       0.2
25                       3.1   10915                       2.6
26                       0.1     320                       0.1
27                       0.0      82                       0.0
28                      44.2  181113                      43.9
29                       0.0      12                       0.0
30                      11.3   47295                      11.5
31                       0.3    1160                       0.3
32                       0.3    1296                       0.3
33                       0.3    1425                       0.3
34                       5.3   21196                       5.1
35                       0.5    1598                       0.4
36                       0.2     704                       0.2
37                       3.6   58576                      14.2
38                      14.3   16666                       4.0
39                     100.0  412959                     100.0
40                     100.0  421104                     100.0

   % Variation during 2019 over 2018

0
1                              600.0
2                                5.2
3                              -73.6
4                              -58.3
5                                  -
6                                  -
7                                  -
8                               89.6
9                               43.1
10                             -34.7
11                              22.0
12                             -31.7
13                             -10.0
14                               6.9
15                              18.2
16
17                             -20.0
18                                 -
19                              -4.4
20                               8.2
21                              10.5
22                              -5.9
23                               3.5
24                              -5.8
25                             -14.4
26                             -39.4
27                             -34.4
28                               1.3
29                             100.0
30                               3.6
31                               1.2
32                              -5.1
33                              26.1
34                              -2.1
35                             -16.8
36                             -19.5
37                             300.3
38                             -71.3
39                               2.0
40                               2.3

In [12]:
# Reset Index before saving file, for better formatting in RAW CSV
tables[0].df.to_csv("Number and Share of Accidental Deaths due to Forces of Nature and Other Causes – 2018 & 2019.csv",index=False)